source 'https://rubygems.org'

ruby '2.2.2'

gem 'activerecord'
gem 'pry'
gem 'minitest'
gem 'rack-test'
gem 'rack-cors'
gem 'tilt'
gem 'erubis'
gem 'sinatra'
gem 'httparty'
gem 'haversine'

group :development do
  gem 'sqlite3'
end

# group :production do
#   gem 'pg'
# end
